apiVersion: automationcontroller.ansible.com/v1beta1  # <--- CHANGED THIS LINE
kind: AutomationController
metadata:
  name: controller
  namespace: ansible-automation-platform
spec:
  replicas: 1
  route_tls_termination_mechanism: Edge
  trash_can_clean_hour: 0
  admin_user: admin